version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: ./app
    container_name: next_app
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - db
